#!/usr/bin/env node
// build-sets.mjs — transform the in-game export (data/sets-export.lua, produced
// by `/esc gen` then copied here) into our baked Lua data files. DEV-ONLY: end
// users get the generated files, never the generator or this script.
//
// Produces:
//   EasySetCollection/Data/SetSources.lua -> global EasySetCollectionSets
//        one entry per set (variant level): content type, dominant sourceType,
//        dominant journalInstanceID, and per-piece instance DEVIATIONS only
//        (a piece from a different instance than the set's dominant one).
//        Display strings are never baked — resolved live, client-localized.
//   EasySetCollection/Data/Instances.lua  -> global EasySetCollectionInstances
//        journalInstanceID -> { raid, tier, map, x, y } (entrance fallback).
//
// Content-type classification (also see Modules/Sources.lua):
//   1. the client's own PvE/PvP sets filter marked the set -> "pvp"
//   2. else majority vote over the pieces' resolved sources, tie-break:
//      raid > dungeon > quest > vendor > world > achievement > profession > tradingpost
//   3. Data/Overrides.lua (`ct` field) wins over everything at runtime.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import luaparse from 'luaparse';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'data', 'sets-export.lua');
const OUT_SETS = join(ROOT, 'EasySetCollection', 'Data', 'SetSources.lua');
const OUT_INST = join(ROOT, 'EasySetCollection', 'Data', 'Instances.lua');

// AppearanceSourceInfo.sourceType luaIndex -> fine-grained content type
const ST_CT = { 2: 'quest', 3: 'vendor', 4: 'world', 5: 'achievement', 6: 'profession', 7: 'tradingpost' };
const CT_PRIORITY = ['raid', 'dungeon', 'quest', 'vendor', 'world', 'achievement', 'profession', 'tradingpost'];

// --- evaluate a luaparse table-literal AST into a plain JS value ---------------
function evalNode(node) {
  switch (node.type) {
    case 'StringLiteral':
      return node.value != null ? node.value : node.raw.slice(1, -1);
    case 'NumericLiteral':
      return node.value;
    case 'BooleanLiteral':
      return node.value;
    case 'NilLiteral':
      return null;
    case 'UnaryExpression':
      return node.operator === '-' ? -evalNode(node.argument) : evalNode(node.argument);
    case 'TableConstructorExpression': {
      const arrayOnly = node.fields.every((f) => f.type === 'TableValue');
      if (arrayOnly) return node.fields.map((f) => evalNode(f.value));
      const obj = {};
      for (const f of node.fields) {
        if (f.type === 'TableKeyString') obj[f.key.name] = evalNode(f.value);
        else if (f.type === 'TableKey') obj[evalNode(f.key)] = evalNode(f.value);
        else obj[obj.__n = (obj.__n || 0) + 1] = evalNode(f.value); // rare positional-in-map
      }
      delete obj.__n;
      return obj;
    }
    default:
      throw new Error('unhandled node: ' + node.type);
  }
}

function readGen() {
  const ast = luaparse.parse(readFileSync(SRC, 'utf8'), { luaVersion: '5.1' });
  for (const stmt of ast.body) {
    if (stmt.type === 'AssignmentStatement'
        && stmt.variables[0]?.type === 'Identifier'
        && stmt.variables[0].name === 'EasySetCollectionGen') {
      return evalNode(stmt.init[0]);
    }
  }
  throw new Error('EasySetCollectionGen not found in ' + SRC);
}

// --- Lua serialization (compact: one line per entry) -----------------------------
function luaStr(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '') + '"';
}
function luaInline(v) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'nil';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return luaStr(v);
  if (Array.isArray(v)) return '{ ' + v.map(luaInline).join(', ') + ' }';
  const parts = Object.entries(v)
    .filter(([, val]) => val !== null && val !== undefined)
    .map(([k, val]) => (/^\d+$/.test(k) ? `[${k}]` : k) + ' = ' + luaInline(val));
  return '{ ' + parts.join(', ') + ' }';
}
function writeKeyedLua(path, globalName, entries, header) {
  const lines = [`-- GENERATED by scripts/build-sets.mjs — DO NOT EDIT BY HAND.`, `-- ${header}`, '', `${globalName} = {`];
  const keys = Object.keys(entries).map(Number).sort((a, b) => a - b);
  for (const k of keys) lines.push(`  [${k}] = ${luaInline(entries[k])},`);
  lines.push('}', '');
  writeFileSync(path, lines.join('\n'));
}

// --- transform -----------------------------------------------------------------
const gen = readGen();
const sets = Array.isArray(gen.sets) ? gen.sets : Object.values(gen.sets || {});
const instMeta = gen.instances || {};

const round1 = (n) => (n == null ? null : Math.round(n * 10) / 10);

// classify one set from its pieces (+ the client-side pvp flag)
function classify(rec) {
  if (rec.pvp) return 'pvp';
  const tally = {};
  const pieces = Array.isArray(rec.pieces) ? rec.pieces : Object.values(rec.pieces || {});
  for (const p of pieces) {
    let ct;
    if (p.j != null) {
      ct = instMeta[p.j]?.raid ? 'raid' : 'dungeon';
    } else {
      ct = ST_CT[p.st];
    }
    if (ct) tally[ct] = (tally[ct] || 0) + 1;
  }
  let best = null, bestCount = -1;
  for (const ct of CT_PRIORITY) {
    const n = tally[ct] || 0;
    if (n > bestCount) { best = ct; bestCount = n; }
  }
  return bestCount > 0 ? best : 'unknown';
}

// dominant value over the pieces (most frequent, ignores null)
function dominant(pieces, get) {
  const counts = new Map();
  for (const p of pieces) {
    const v = get(p);
    if (v != null) counts.set(v, (counts.get(v) || 0) + 1);
  }
  let best = null, bestCount = 0;
  for (const [v, n] of counts) if (n > bestCount) { best = v; bestCount = n; }
  return best;
}

// itemID -> questID: Wowhead import (fetch-quest-sources.mjs) filled in with —
// and overridden by — the in-game /esc genquests sweep (verified client data)
const questRewards = {};
const WOWHEAD_SRC = join(ROOT, 'data', 'quest-sources.json');
if (existsSync(WOWHEAD_SRC)) {
  for (const [itemID, questID] of Object.entries(JSON.parse(readFileSync(WOWHEAD_SRC, 'utf8')))) {
    if (questID != null) questRewards[itemID] = questID;
  }
}
Object.assign(questRewards, gen.questRewards || {});
const qOf = (p) => (p.st === 2 && p.itemID != null ? questRewards[p.itemID] ?? null : null);

const outSets = {};
let piecesKept = 0, piecesTotal = 0, questPieces = 0, questMatched = 0;
for (const rec of sets) {
  const pieces = Array.isArray(rec.pieces) ? rec.pieces : Object.values(rec.pieces || {});
  piecesTotal += pieces.length;
  const entry = {
    ct: classify(rec),
    st: dominant(pieces, (p) => p.st),
    j: dominant(pieces, (p) => p.j),
    q: dominant(pieces, qOf),          // dominant quest of the quest pieces
  };
  // bake only the deviations: a piece whose instance/quest differs from the
  // set's dominant one (runtime falls back to the set-level values and
  // resolves everything else live)
  const dev = {};
  let nDev = 0;
  for (const p of pieces) {
    if (p.st === 2) {
      questPieces++;
      if (qOf(p) != null) questMatched++;
    }
    const d = {};
    if (p.j != null && p.j !== entry.j) d.j = p.j;
    const qv = qOf(p);
    if (qv != null && qv !== entry.q) d.q = qv;
    if (p.sid != null && Object.keys(d).length) {
      dev[p.sid] = d;
      nDev++;
    }
  }
  if (nDev > 0) { entry.pieces = dev; piecesKept += nDev; }
  outSets[rec.setID] = entry;
}

const outInst = {};
for (const [jid, m] of Object.entries(instMeta)) {
  outInst[jid] = {
    raid: m.raid ? true : null,
    tier: m.tier ?? null,
    map: m.map ?? null,
    x: round1(m.x),
    y: round1(m.y),
  };
}

writeKeyedLua(OUT_SETS, 'EasySetCollectionSets', outSets,
  'One entry per transmog set (variant level): content type, dominant sourceType/instance, per-piece instance deviations.');
writeKeyedLua(OUT_INST, 'EasySetCollectionInstances', outInst,
  'journalInstanceID -> raid flag, EJ tier, entrance harvested at generation time (0-100 coords).');

// --- report --------------------------------------------------------------------
const byCt = {};
for (const e of Object.values(outSets)) byCt[e.ct] = (byCt[e.ct] || 0) + 1;
console.log(`sets:      ${Object.keys(outSets).length} (${Object.entries(byCt).map(([k, n]) => `${k}=${n}`).join(', ')}) -> ${OUT_SETS}`);
console.log(`instances: ${Object.keys(outInst).length} -> ${OUT_INST}`);
console.log(`pieces:    ${piecesTotal} scanned, ${piecesKept} deviation records baked`);
if (questPieces) {
  console.log(`quests:    ${questMatched}/${questPieces} quest pieces matched to a questID`
    + (Object.keys(questRewards).length ? '' : ' (run /esc genquests in game to fill this)'));
}

const unresolved = Array.isArray(gen.unresolved) ? gen.unresolved : Object.values(gen.unresolved || {});
if (unresolved.length) {
  console.log(`WARN ${unresolved.length} boss-drop piece(s) not matched to an EJ instance (candidates for Data/Overrides.lua):`);
  const byInst = {};
  for (const u of unresolved) byInst[u.instance || u.reason || '?'] = (byInst[u.instance || u.reason || '?'] || 0) + 1;
  for (const [name, n] of Object.entries(byInst).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${String(n).padStart(4)} × ${name}`);
  }
}
const noNav = Object.values(outSets).filter((e) => e.j == null && e.ct !== 'unknown').length;
console.log(`note:      ${noNav} set(s) have no instance target (quest/vendor/pvp/world) — add coords to Data/Overrides.lua as needed.`);
