#!/usr/bin/env node
// build-sets.mjs — transform the in-game export (data/sets-export.lua, produced
// by `/esc gen` then copied here) into our baked Lua data files. DEV-ONLY: end
// users get the generated files, never the generator or this script.
//
// Produces:
//   EasySetCollection/Data/SetSources.lua -> global EasySetCollectionSets
//        one entry per set (variant level): content type, dominant sourceType,
//        dominant journalInstanceID, and per-piece instance DEVIATIONS only
//        (a piece from a different instance than the set's dominant one).
//        Display strings are never baked — resolved live, client-localized.
//   EasySetCollection/Data/Instances.lua  -> global EasySetCollectionInstances
//        journalInstanceID -> { raid, tier, map, x, y } (entrance fallback).
//
// Content-type classification (also see Modules/Sources.lua):
//   1. the client's own PvE/PvP sets filter marked the set -> "pvp"
//   2. else majority vote over the pieces' resolved sources, tie-break:
//      raid > dungeon > quest > vendor > world > achievement > profession > tradingpost
//   3. Data/Overrides.lua (`ct` field) wins over everything at runtime.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import luaparse from 'luaparse';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'data', 'sets-export.lua');
const OUT_SETS = join(ROOT, 'EasySetCollection', 'Data', 'SetSources.lua');
const OUT_INST = join(ROOT, 'EasySetCollection', 'Data', 'Instances.lua');

// AppearanceSourceInfo.sourceType luaIndex -> fine-grained content type
const ST_CT = { 2: 'quest', 3: 'vendor', 4: 'world', 5: 'achievement', 6: 'profession', 7: 'tradingpost' };
const CT_PRIORITY = ['raid', 'dungeon', 'quest', 'vendor', 'world', 'achievement', 'profession', 'tradingpost'];

// --- evaluate a luaparse table-literal AST into a plain JS value ---------------
function evalNode(node) {
  switch (node.type) {
    case 'StringLiteral':
      return node.value != null ? node.value : node.raw.slice(1, -1);
    case 'NumericLiteral':
      return node.value;
    case 'BooleanLiteral':
      return node.value;
    case 'NilLiteral':
      return null;
    case 'UnaryExpression':
      return node.operator === '-' ? -evalNode(node.argument) : evalNode(node.argument);
    case 'TableConstructorExpression': {
      const arrayOnly = node.fields.every((f) => f.type === 'TableValue');
      if (arrayOnly) return node.fields.map((f) => evalNode(f.value));
      const obj = {};
      for (const f of node.fields) {
        if (f.type === 'TableKeyString') obj[f.key.name] = evalNode(f.value);
        else if (f.type === 'TableKey') obj[evalNode(f.key)] = evalNode(f.value);
        else obj[obj.__n = (obj.__n || 0) + 1] = evalNode(f.value); // rare positional-in-map
      }
      delete obj.__n;
      return obj;
    }
    default:
      throw new Error('unhandled node: ' + node.type);
  }
}

function readGen() {
  const ast = luaparse.parse(readFileSync(SRC, 'utf8'), { luaVersion: '5.1' });
  for (const stmt of ast.body) {
    if (stmt.type === 'AssignmentStatement'
        && stmt.variables[0]?.type === 'Identifier'
        && stmt.variables[0].name === 'EasySetCollectionGen') {
      return evalNode(stmt.init[0]);
    }
  }
  throw new Error('EasySetCollectionGen not found in ' + SRC);
}

// --- Lua serialization (compact: one line per entry) -----------------------------
function luaStr(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '') + '"';
}
function luaInline(v) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'nil';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return luaStr(v);
  if (Array.isArray(v)) return '{ ' + v.map(luaInline).join(', ') + ' }';
  const parts = Object.entries(v)
    .filter(([, val]) => val !== null && val !== undefined)
    .map(([k, val]) => (/^\d+$/.test(k) ? `[${k}]` : k) + ' = ' + luaInline(val));
  return '{ ' + parts.join(', ') + ' }';
}
function writeKeyedLua(path, globalName, entries, header) {
  const lines = [`-- GENERATED by scripts/build-sets.mjs — DO NOT EDIT BY HAND.`, `-- ${header}`, '', `${globalName} = {`];
  const keys = Object.keys(entries).map(Number).sort((a, b) => a - b);
  for (const k of keys) lines.push(`  [${k}] = ${luaInline(entries[k])},`);
  lines.push('}', '');
  writeFileSync(path, lines.join('\n'));
}

// --- transform -----------------------------------------------------------------
const gen = readGen();
const sets = Array.isArray(gen.sets) ? gen.sets : Object.values(gen.sets || {});
const instMeta = gen.instances || {};

const round1 = (n) => (n == null ? null : Math.round(n * 10) / 10);

// classify one set from its pieces (+ the client-side pvp flag)
function classify(rec) {
  if (rec.pvp) return 'pvp';
  const tally = {};
  const pieces = Array.isArray(rec.pieces) ? rec.pieces : Object.values(rec.pieces || {});
  for (const p of pieces) {
    let ct;
    if (p.j != null) {
      ct = instMeta[p.j]?.raid ? 'raid' : 'dungeon';
    } else {
      ct = ST_CT[p.st];
    }
    if (ct) tally[ct] = (tally[ct] || 0) + 1;
  }
  let best = null, bestCount = -1;
  for (const ct of CT_PRIORITY) {
    const n = tally[ct] || 0;
    if (n > bestCount) { best = ct; bestCount = n; }
  }
  return bestCount > 0 ? best : 'unknown';
}

// dominant value over the pieces (most frequent, ignores null)
function dominant(pieces, get) {
  const counts = new Map();
  for (const p of pieces) {
    const v = get(p);
    if (v != null) counts.set(v, (counts.get(v) || 0) + 1);
  }
  let best = null, bestCount = 0;
  for (const [v, n] of counts) if (n > bestCount) { best = v; bestCount = n; }
  return best;
}

// itemID -> questID: Wowhead import (fetch-quest-sources.mjs) filled in with —
// and overridden by — the in-game /esc genquests sweep (verified client data)
const questRewards = {};
const WOWHEAD_SRC = join(ROOT, 'data', 'quest-sources.json');
if (existsSync(WOWHEAD_SRC)) {
  for (const [itemID, questID] of Object.entries(JSON.parse(readFileSync(WOWHEAD_SRC, 'utf8')))) {
    if (questID != null) questRewards[itemID] = questID;
  }
}
Object.assign(questRewards, gen.questRewards || {});
const qOf = (p) => (p.st === 2 && p.itemID != null ? questRewards[p.itemID] ?? null : null);

const outSets = {};
let piecesKept = 0, piecesTotal = 0, questPieces = 0, questMatched = 0;
for (const rec of sets) {
  const pieces = Array.isArray(rec.pieces) ? rec.pieces : Object.values(rec.pieces || {});
  piecesTotal += pieces.length;
  const entry = {
    ct: classify(rec),
    st: dominant(pieces, (p) => p.st),
    j: dominant(pieces, (p) => p.j),
    q: dominant(pieces, qOf),          // dominant quest of the quest pieces
  };
  // bake only the deviations: a piece whose instance/quest differs from the
  // set's dominant one (runtime falls back to the set-level values and
  // resolves everything else live)
  const dev = {};
  let nDev = 0;
  for (const p of pieces) {
    if (p.st === 2) {
      questPieces++;
      if (qOf(p) != null) questMatched++;
    }
    const d = {};
    if (p.j != null && p.j !== entry.j) d.j = p.j;
    const qv = qOf(p);
    if (qv != null && qv !== entry.q) d.q = qv;
    if (p.sid != null && Object.keys(d).length) {
      dev[p.sid] = d;
      nDev++;
    }
  }
  if (nDev > 0) { entry.pieces = dev; piecesKept += nDev; }
  outSets[rec.setID] = entry;
}

const outInst = {};
for (const [jid, m] of Object.entries(instMeta)) {
  outInst[jid] = {
    raid: m.raid ? true : null,
    tier: m.tier ?? null,
    map: m.map ?? null,
    x: round1(m.x),
    y: round1(m.y),
  };
}

writeKeyedLua(OUT_SETS, 'EasySetCollectionSets', outSets,
  'One entry per transmog set (variant level): content type, dominant sourceType/instance, per-piece instance deviations.');
writeKeyedLua(OUT_INST, 'EasySetCollectionInstances', outInst,
  'journalInstanceID -> raid flag, EJ tier, entrance harvested at generation time (0-100 coords).');

// --- vendors ---------------------------------------------------------------
// vendor-sources.json / npc-locations.json come from fetch-vendor-sources.mjs;
// zone-uimap.json is the hand-authored Wowhead-zone(AreaTable id) -> uiMapID
// table (Wowhead's 0-100 coords line up with the in-game zone maps).
const OUT_VEND = join(ROOT, 'EasySetCollection', 'Data', 'Vendors.lua');
const VEND_SRC = join(ROOT, 'data', 'vendor-sources.json');
const NPC_SRC = join(ROOT, 'data', 'npc-locations.json');
const ZONE_SRC = join(ROOT, 'data', 'zone-uimap.json');

// faction side from a Wowhead react pair: 1=Alliance, 2=Horde, 3=both
function sideOf(react) {
  if (!Array.isArray(react)) return 3;
  const a = (react[0] || 0) > 0, h = (react[1] || 0) > 0;
  if (a && !h) return 1;
  if (h && !a) return 2;
  return 3;
}

let vendReport = null;
if (existsSync(VEND_SRC)) {
  const vendCache = JSON.parse(readFileSync(VEND_SRC, 'utf8'));
  const npcCache = existsSync(NPC_SRC) ? JSON.parse(readFileSync(NPC_SRC, 'utf8')) : {};
  const zoneMap = existsSync(ZONE_SRC) ? JSON.parse(readFileSync(ZONE_SRC, 'utf8')) : {};

  // one vendor per side per set: located (zone-mapped) rows first, then popularity
  const vendSets = {};
  const usedNpcs = new Set();
  for (const rec of sets) {
    const pieces = Array.isArray(rec.pieces) ? rec.pieces : Object.values(rec.pieces || {});
    const items = pieces.filter((p) => p.st === 3 && p.itemID != null).map((p) => p.itemID);
    if (!items.length || items.length <= pieces.length / 2) continue;
    let rows = null;
    for (const itemID of items) {
      const cached = vendCache[itemID];
      if (Array.isArray(cached) && cached.length) { rows = cached; break; }
    }
    if (!rows) continue;
    const bySide = {};
    for (const r of rows) {
      const npc = npcCache[r.id];
      const located = npc && npc.zone != null && zoneMap[npc.zone] != null;
      const rank = (located ? 1e6 : 0) + (r.pop || 0);
      const s = sideOf(r.react);
      if (!bySide[s] || rank > bySide[s].rank) bySide[s] = { row: r, rank };
    }
    const picked = bySide[3] ? [bySide[3]] : [bySide[1], bySide[2]].filter(Boolean);
    if (!picked.length) continue;
    vendSets[rec.setID] = picked.map((e) => {
      usedNpcs.add(e.row.id);
      const s = sideOf(e.row.react);
      return { n: e.row.id, s: s === 3 ? null : s };
    });
  }

  const vendNpcs = {};
  const unmappedZones = new Map();
  let located = 0;
  for (const id of usedNpcs) {
    const npc = npcCache[id] || {};
    const map = npc.zone != null ? zoneMap[npc.zone] : null;
    if (npc.zone != null && map == null) {
      const u = unmappedZones.get(npc.zone) || { count: 0, sample: npc.name };
      u.count++;
      unmappedZones.set(npc.zone, u);
    }
    if (map != null) located++;
    vendNpcs[id] = {
      name: npc.name || '#' + id,
      map: map ?? null,
      x: map != null ? npc.x : null,
      y: map != null ? npc.y : null,
    };
  }

  // per-item price: gold (copper), token items, currencies
  const vendCosts = {};
  for (const [itemID, rows] of Object.entries(vendCache)) {
    if (!Array.isArray(rows) || !rows.length) continue;
    const cost = rows[0].cost && rows[0].cost[0];
    if (!Array.isArray(cost)) continue;
    const [gold, itemCost, curCost] = cost;
    const e = {};
    if (gold > 0) e.g = gold;
    if (Array.isArray(itemCost) && itemCost.length) e.i = itemCost;
    if (Array.isArray(curCost) && curCost.length) e.c = curCost;
    if (Object.keys(e).length) vendCosts[itemID] = e;
  }

  const lines = [
    '-- GENERATED by scripts/build-sets.mjs — DO NOT EDIT BY HAND.',
    '-- Baked vendor layer: selling NPCs (English name + uiMapID/coords), which',
    '-- variant set each one sells, and per-item prices (copper / currencies /',
    '-- token items). Ships empty until the first generation; the runtime treats',
    '-- every lookup as optional.',
    '',
    'EasySetCollectionVendors = {',
  ];
  const pushKeyed = (label, entries) => {
    lines.push(`  ${label} = {`);
    for (const k of Object.keys(entries).map(Number).sort((a, b) => a - b)) {
      lines.push(`    [${k}] = ${luaInline(entries[k])},`);
    }
    lines.push('  },');
  };
  pushKeyed('npcs', vendNpcs);
  pushKeyed('sets', vendSets);
  pushKeyed('costs', vendCosts);
  lines.push('}', '');
  writeFileSync(OUT_VEND, lines.join('\n'));

  vendReport = { sets: Object.keys(vendSets).length, npcs: usedNpcs.size, located,
    costs: Object.keys(vendCosts).length, unmappedZones };
}

// --- report --------------------------------------------------------------------
const byCt = {};
for (const e of Object.values(outSets)) byCt[e.ct] = (byCt[e.ct] || 0) + 1;
console.log(`sets:      ${Object.keys(outSets).length} (${Object.entries(byCt).map(([k, n]) => `${k}=${n}`).join(', ')}) -> ${OUT_SETS}`);
console.log(`instances: ${Object.keys(outInst).length} -> ${OUT_INST}`);
console.log(`pieces:    ${piecesTotal} scanned, ${piecesKept} deviation records baked`);
// --- extra sets (out-of-journal, Wowhead import) -----------------------------------
// data/extra-sets.json comes from fetch-extra-sets.mjs. The subcategory id
// (`cat`, a Wowhead facet option) maps to our filter buckets here; sets with
// no category bake bucket-less and classify at runtime from their items.
const OUT_EXTRA = join(ROOT, 'EasySetCollection', 'Data', 'ExtraSets.lua');
const EXTRA_SRC = join(ROOT, 'data', 'extra-sets.json');

const CAT_BUCKET = {};
for (const id of [45, 1, 2, 14, 47, 48, 50, 46, 49, 51, 52, 67, 76, 77, 87, 98, 122, 124]) CAT_BUCKET[id] = 'dungeon';
for (const id of [57, 3, 4, 5, 12, 13, 18, 23, 25, 27, 29, 31, 35, 38, 39, 43, 64, 65, 71, 78,
                  82, 86, 88, 94, 9, 10, 11, 58, 59, 70, 61, 99, 100, 101, 110, 113, 116, 117, 126]) CAT_BUCKET[id] = 'raid';
for (const id of [17, 19, 20, 22, 24, 26, 28, 30, 33, 34, 37, 40, 42, 62, 63, 66, 72, 73, 80, 79,
                  83, 85, 89, 93, 103, 104, 105, 111, 114, 6, 8, 16, 21, 36, 32, 41, 118, 119, 125]) CAT_BUCKET[id] = 'pvp';
for (const id of [53, 54, 55, 56, 68, 75, 81, 84, 92, 102, 115, 123, 127]) CAT_BUCKET[id] = 'quest';
for (const id of [74, 60, 91, 120]) CAT_BUCKET[id] = 'world';   // invasion/island/storm events
CAT_BUCKET[121] = 'vendor';                                     // Trading Post
for (const id of [106, 107, 108, 109]) CAT_BUCKET[id] = 'vendor'; // covenant sets

let extraReport = null;
if (existsSync(EXTRA_SRC)) {
  const extra = JSON.parse(readFileSync(EXTRA_SRC, 'utf8')).sets || {};
  const outExtra = {};
  let buckets = 0;
  for (const [wid, s] of Object.entries(extra)) {
    const b = s.cat != null ? CAT_BUCKET[s.cat] || null : null;
    if (b) buckets++;
    outExtra[wid] = {
      name: s.name,
      e: s.exp != null ? s.exp - 1 : null,   // facet option 1..12 -> expansionID 0..11
      at: s.at ?? null,
      rc: s.rc || null,
      b,
      items: s.pieces,
    };
  }
  const lines = [
    '-- GENERATED by scripts/build-sets.mjs — DO NOT EDIT BY HAND.',
    '-- Out-of-journal transmog sets (Wowhead import, fetch-extra-sets.mjs):',
    '-- community English names, expansionID, armor type, class bitmask, filter',
    '-- bucket and piece itemIDs. The runtime shows them as synthetic catalog',
    '-- groups keyed by NEGATIVE setIDs (-wowheadID); appearance/source data',
    '-- resolves live from the items.',
    '',
    'EasySetCollectionExtraSets = {',
  ];
  for (const k of Object.keys(outExtra).map(Number).sort((a, b) => a - b)) {
    lines.push(`  [${k}] = ${luaInline(outExtra[k])},`);
  }
  lines.push('}', '');
  writeFileSync(OUT_EXTRA, lines.join('\n'));
  extraReport = { total: Object.keys(outExtra).length, buckets };
}

if (questPieces) {
  console.log(`quests:    ${questMatched}/${questPieces} quest pieces matched to a questID`
    + (Object.keys(questRewards).length ? '' : ' (run /esc genquests in game to fill this)'));
}
if (extraReport) {
  console.log(`extras:    ${extraReport.total} out-of-journal sets baked (${extraReport.buckets} with a bucket) -> ${OUT_EXTRA}`);
}
if (vendReport) {
  console.log(`vendors:   ${vendReport.sets} sets -> a selling NPC (${vendReport.npcs} npcs, `
    + `${vendReport.located} located), ${vendReport.costs} piece prices -> ${OUT_VEND}`);
  if (vendReport.unmappedZones.size) {
    console.log(`WARN ${vendReport.unmappedZones.size} Wowhead zone(s) without a uiMapID — their vendors bake name-only.`);
    console.log('     Add them to data/zone-uimap.json:');
    for (const [zone, u] of [...vendReport.unmappedZones].sort((a, b) => b[1].count - a[1].count)) {
      console.log(`  ${String(u.count).padStart(4)} npc(s) in zone ${zone} (e.g. "${u.sample}") — https://www.wowhead.com/zone=${zone}`);
    }
  }
}

const unresolved = Array.isArray(gen.unresolved) ? gen.unresolved : Object.values(gen.unresolved || {});
if (unresolved.length) {
  console.log(`WARN ${unresolved.length} boss-drop piece(s) not matched to an EJ instance (candidates for Data/Overrides.lua):`);
  const byInst = {};
  for (const u of unresolved) byInst[u.instance || u.reason || '?'] = (byInst[u.instance || u.reason || '?'] || 0) + 1;
  for (const [name, n] of Object.entries(byInst).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${String(n).padStart(4)} × ${name}`);
  }
}
const noNav = Object.values(outSets).filter((e) => e.j == null && e.ct !== 'unknown').length;
console.log(`note:      ${noNav} set(s) have no instance target (quest/vendor/pvp/world) — add coords to Data/Overrides.lua as needed.`);
