-- GENERATED by scripts/build-sets.mjs — DO NOT EDIT BY HAND.
-- Baked vendor layer: selling NPCs (English name + uiMapID/coords), which
-- variant set each one sells, and per-item prices (copper / currencies /
-- token items). Ships empty until the first generation; the runtime treats
-- every lookup as optional.

EasySetCollectionVendors = {
  npcs = {},
  sets = {},
  costs = {},
}
